package controller

import "strings"

var giftTranslations = map[string]string{
	"rose":             "Rosa",
	"heart":            "Coração",
	"hand heart":       "Coração de Mão",
	"finger heart":     "Coração de Dedo",
	"love heart":       "Coração de Amor",
	"beating heart":    "Coração Batendo",
	"heartbeat":        "Batimento",
	"sunglasses":       "Óculos de Sol",
	"mirror":           "Espelho",
	"cap":              "Boné",
	"hat":              "Chapéu",
	"money gun":        "Metralhadora de Dinheiro",
	"galaxy":           "Galáxia",
	"lion":             "Leão",
	"helicopter":       "Helicóptero",
	"race car":         "Carro de Corrida",
	"sports car":       "Carro Esportivo",
	"rocket":           "Foguete",
	"confetti":         "Confete",
	"fireworks":        "Fogos de Artifício",
	"disc":             "Disco",
	"disco":            "Discoteca",
	"gift box":         "Caixa de Presente",
	"present box":      "Caixa de Presente",
	"handbag":          "Bolsa",
	"crown":            "Coroa",
	"castle":           "Castelo",
	"whale":            "Baleia",
	"dolphin":          "Golfinho",
	"star":             "Estrela",
	"microphone":       "Microfone",
	"mic":              "Microfone",
	"basketball":       "Basquete",
	"football":         "Futebol Americano",
	"soccer":           "Futebol",
	"love bang":        "Bomba de Amor",
	"love letter":      "Carta de Amor",
	"i love you":       "Eu Te Amo",
	"applause":         "Palmas",
	"clap":             "Palmas",
	"bravo":            "Bravo",
	"kiss":             "Beijo",
	"hug":              "Abraço",
	"wave":             "Aceno",
	"wink":             "Piscadela",
	"party":            "Festa",
	"magic":            "Mágica",
	"lucky":            "Sorte",
	"treasure":         "Tesouro",
	"money":            "Dinheiro",
	"coin":             "Moeda",
	"cash":             "Dinheiro",
	"dollar":           "Dólar",
	"butterfly":        "Borboleta",
	"ladybug":          "Joaninha",
	"bee":              "Abelha",
	"panda":            "Panda",
	"penguin":          "Pinguim",
	"owl":              "Coruja",
	"dog":              "Cachorro",
	"puppy":            "Cachorrinho",
	"cat":              "Gato",
	"kitten":           "Gatinho",
	"bunny":            "Coelho",
	"rabbit":           "Coelho",
	"bear":             "Urso",
	"teddy bear":       "Urso de Pelúcia",
	"monkey":           "Macaco",
	"frog":             "Sapo",
	"turtle":           "Tartaruga",
	"fish":             "Peixe",
	"shark":            "Tubarão",
	"octopus":          "Polvo",
	"crab":             "Caranguejo",
	"dinosaur":         "Dinossauro",
	"dragon":           "Dragão",
	"unicorn":          "Unicórnio",
	"phoenix":          "Fênix",
	"eagle":            "Águia",
	"bird":             "Pássaro",
	"duck":             "Pato",
	"horse":            "Cavalo",
	"cow":              "Vaca",
	"pig":              "Porco",
	"sheep":            "Ovelha",
	"snake":            "Cobra",
	"elephant":         "Elefante",
	"giraffe":          "Girafa",
	"tiger":            "Tigre",
	"fox":              "Raposa",
	"wolf":             "Lobo",
	"hamster":          "Hamster",
	"hedgehog":         "Ouriço",
	"snail":            "Caracol",
	"koala":            "Coala",
	"parrot":           "Papagaio",
	"beer":             "Cerveja",
	"cocktail":         "Coquetel",
	"coffee":           "Café",
	"cake":             "Bolo",
	"ice cream":        "Sorvete",
	"pizza":            "Pizza",
	"burger":           "Hambúrguer",
	"popcorn":          "Pipoca",
	"donut":            "Rosquinha",
	"chocolate":        "Chocolate",
	"candy":            "Doce",
	"apple":            "Maçã",
	"banana":           "Banana",
	"grapes":           "Uvas",
	"strawberry":       "Morango",
	"watermelon":       "Melancia",
	"cherry":           "Cereja",
	"lemon":            "Limão",
	"orange":           "Laranja",
	"coconut":          "Coco",
	"pineapple":        "Abacaxi",
	"mango":            "Manga",
	"juice":            "Suco",
	"milk":             "Leite",
	"tea":              "Chá",
	"wine":             "Vinho",
	"champagne":        "Champanhe",
	"bread":            "Pão",
	"cheese":           "Queijo",
	"egg":              "Ovo",
	"noodles":          "Macarrão",
	"rice":             "Arroz",
	"soup":             "Sopa",
	"sushi":            "Sushi",
	"taco":             "Taco",
	"hot dog":          "Cachorro-quente",
	"diamond":          "Diamante",
	"gold":             "Ouro",
	"gold bar":         "Barra de Ouro",
	"jewelry":          "Joia",
	"necklace":         "Colar",
	"ring":             "Anel",
	"earrings":         "Brincos",
	"watch":            "Relógio",
	"boots":            "Botas",
	"dress":            "Vestido",
	"suit":             "Terno",
	"t-shirt":          "Camiseta",
	"key":              "Chave",
	"lock":             "Cadeado",
	"gift":             "Presente",
	"balloon":          "Balão",
	"umbrella":         "Guarda-chuva",
	"camera":           "Câmera",
	"phone":            "Telefone",
	"trophy":           "Troféu",
	"medal":            "Medalha",
	"flag":             "Bandeira",
	"map":              "Mapa",
	"compass":          "Bússola",
	"telescope":        "Telescópio",
	"book":             "Livro",
	"pencil":           "Lápis",
	"pen":              "Caneta",
	"guitar":           "Violão",
	"piano":            "Piano",
	"drum":             "Bateria",
	"trumpet":          "Trompete",
	"violin":           "Violino",
	"rainbow":          "Arco-íris",
	"sun":              "Sol",
	"moon":             "Lua",
	"cloud":            "Nuvem",
	"lightning":        "Raio",
	"rain":             "Chuva",
	"snow":             "Neve",
	"snowflake":        "Floco de Neve",
	"leaf":             "Folha",
	"tree":             "Árvore",
	"cactus":           "Cacto",
	"mushroom":         "Cogumelo",
	"shell":            "Concha",
	"crystal":          "Cristal",
	"pearl":            "Pérola",
	"drama queen":      "Rainha do Drama",
	"flower":           "Flor",
	"bouquet":          "Buquê",
	"gift card":        "Cartão de Presente",
	"perfume":          "Perfume",
}

func translateGiftName(name string) string {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return name
	}
	if translated, ok := giftTranslations[strings.ToLower(trimmed)]; ok {
		return translated
	}
	return trimmed
}
